export const ADD_TO_CHART = 'ADD_TO_CHART';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID';
export const CHART_ITEM_COUNT_INCREASE = 'CHART_ITEM_COUNT_INCREASE';
export const CHART_ITEM_COUNT_DECREASE = 'CHART_ITEM_COUNT_DECREASE';
export const CHART_ITEM_REMOVE = 'CHART_ITEM_REMOVE';
export const CHECKOUT = 'CHECKOUT';
